---
language: node_js
node_js:
  - 12.13.0

install:
  # Install Pulumi SDK with the installation script from https://www.pulumi.com/docs/get-started/install/#installation-script
  - curl -fsSL https://get.pulumi.com | sh
  # Add Pulumi to Travis' PATH so the executable could be found
  - export PATH=$PATH:/home/travis/.pulumi/bin
  - pulumi version

  # Install pulumi-aws dependencies (among others like awscli) via npm dependency manager
  - npm install
  # Check, if Pulumi aws plugin was installed correctly
  - pulumi plugin ls

script:
  # login to app.pulumi.com with the predefined PULUMI_ACCESS_TOKEN
  - pulumi login

  # Select your Pulumi projects' stack
  - pulumi stack select dev

  # Create AWS Fargate application deployment
  - pulumi up --yes

  # Destroy Pulumi setup after successful creation
  - pulumi destroy --yes